spring:
  application:
    #应用服务名格式为：应用名-app
    name: disaster-web
  profiles:
    active: dev
server:
  port: 8080
  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
#=========================使用注册中心的服务============
#启用注册中心客户端
eureka:
  client:
    enabled: true
  instance:
    prefer-ip-address: true